server:
  port: 8988
spring:
  devtools:
    restart:
      # 设置开启热部署
      enabled: true
      additional-paths: src/main
  # 模板配置
  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
  servlet:
    multipart:
      # 是否支持批量上传   (默认值 true)
      enabled: true
      resolve-lazily: false
# 开启日志
debug: true
# 日志记录级别
logging:
  level:
    # root日志以WARN级别输出
    root: warn
    com:
      example:
        ftp_demo: debug
    # 去掉 CONDITIONS EVALUATION REPORT
    org:
      springframework:
        boot:
          autoconfigure: error
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-64
  # 是否输出操作日志
  is-log: false